Repository ispp-yourney/yourney-backend, pull requests merged in 2021-05, with the labels that each got.

#152 Configuración de Postgresql y corrección de errores menores
  .travis.yml
  src/main/resources/mail/index.html
  src/test/java/com/yourney/controller/ActivityControllerTests.java
Labels: bug, configuration

#153 Feature issue#150
  src/main/resources/db/data.sql
  src/main/resources/mail/index.html
Labels: enhancement

#154 Puesta en producción de las funcionalidades del tercer sprint
  .travis.yml
  pom.xml
  src/main/java/com/yourney/YourneyBackendApplication.java
  src/main/java/com/yourney/controller/ActivityController.java
  src/main/java/com/yourney/controller/CommentController.java
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/ItineraryVisit.java
  src/main/java/com/yourney/model/Landmark.java
  src/main/java/com/yourney/model/LandmarkVisit.java
  src/main/java/com/yourney/model/projection/ItineraryProjection.java
  src/main/java/com/yourney/repository/ActivityRepository.java
  src/main/java/com/yourney/repository/ItineraryRepository.java
  src/main/java/com/yourney/repository/ItineraryVisitRepository.java
  src/main/java/com/yourney/repository/LandmarkRepository.java
  src/main/java/com/yourney/repository/LandmarkVisitRepository.java
  src/main/java/com/yourney/security/controller/AuthController.java
  src/main/java/com/yourney/security/exception/UnverifiedUserException.java
  src/main/java/com/yourney/security/model/SecureToken.java
  src/main/java/com/yourney/security/model/User.java
  src/main/java/com/yourney/security/repository/SecureTokenRepository.java
  src/main/java/com/yourney/security/service/SecureTokenService.java
  src/main/java/com/yourney/security/service/UserDetailsServiceImpl.java
  src/main/java/com/yourney/security/service/UserService.java
  src/main/java/com/yourney/service/ItineraryService.java
  src/main/java/com/yourney/service/ItineraryVisitService.java
  src/main/java/com/yourney/service/LandmarkService.java
  src/main/java/com/yourney/service/LandmarkVisitService.java
  src/main/resources/application-dev.properties
  src/main/resources/application-gen.properties
  src/main/resources/application-prod.properties
  src/main/resources/application-production.properties
  src/main/resources/application.properties
  src/main/resources/db/data.sql
  src/main/resources/db/migration/V1__create.sql
  src/main/resources/db/migration/V2__data.sql
  src/main/resources/mail/index.html
  src/main/resources/templates/banner.txt
  src/test/java/com/yourney/controller/ActivityControllerTests.java
  src/test/java/com/yourney/controller/AuthControllerTests.java
  src/test/java/com/yourney/controller/CommentControllerTests.java
  src/test/java/com/yourney/controller/ItineraryControllerTests.java
  src/test/java/com/yourney/controller/LandmarkControllerTests.java
  src/test/java/com/yourney/model/ItineraryVisitModelTests.java
  src/test/java/com/yourney/model/LandmarkVisitModelTests.java
  src/test/java/com/yourney/service/ItineraryServiceTests.java
  src/test/java/com/yourney/service/LandmarkServiceTests.java
Labels: enhancement

#156 Se han cambiado las URLs de despliegue
  src/main/resources/application.properties
Labels: bug, configuration

#157 Hotfix: Configuración de despliegue para el sprint 3
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__create.sql
  src/main/resources/db/migration/V2__data.sql
Labels: bug

#158 Revert de "Hotfix: Configuración de despliegue para el sprint 3"
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__create.sql
  src/main/resources/db/migration/V2__data.sql
Labels: bug

#160 Hotfix: Puesta en producción del sprint 3
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__create.sql
  src/main/resources/db/migration/V2__data.sql
Labels: bug, configuration

#162 Actualizada imagen por defecto
  src/main/resources/db/data.sql
Labels: bug

#164 Eliminación de visitas de itinerarios y puntos de interés
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/repository/ItineraryVisitRepository.java
  src/main/java/com/yourney/repository/LandmarkVisitRepository.java
  src/main/java/com/yourney/service/ItineraryVisitService.java
  src/main/java/com/yourney/service/LandmarkVisitService.java
Labels: bug

#166 Cambio en la autoría de un comentario
  src/main/resources/db/data.sql
Labels: bug

#168 Puesta en producción de las funcionalidades de la fase Preparing Project Launch
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/repository/ItineraryVisitRepository.java
  src/main/java/com/yourney/repository/LandmarkVisitRepository.java
  src/main/java/com/yourney/service/ItineraryVisitService.java
  src/main/java/com/yourney/service/LandmarkVisitService.java
  src/main/resources/application.properties
  src/main/resources/db/data.sql
Labels: bug, enhancement

#169 Persistencia de la base de datos y direcciones de redireccionamiento
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__create.sql
  src/main/resources/db/migration/V2__data.sql
Labels: bug

#172 Corregido error en un comentario
  src/main/resources/db/data.sql
  src/main/resources/db/migration/V2__data.sql
Labels: bug

#173 Corregido error en un comentario
  src/main/resources/db/data.sql
  src/main/resources/db/migration/V2__data.sql
Labels: bug

#175 Actualizadas direcciones de redireccionamiento
  src/main/resources/application.properties
Labels: bug
