Repository ispp-yourney/yourney-backend, pull requests merged in 2021-04, with the labels that each got.

#52 Introducción de datos de prueba
  src/main/java/com/yourney/model/Activity.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/Landmark.java
  src/main/resources/db/data.sql
Labels: enhancement

#53 Introducción de datos de prueba
  src/main/resources/db/data.sql
Labels: enhancement

#54 Feature 39
  pom.xml
  src/main/resources/db/data.sql
  src/test/java/com/yourney/controller/ActivityControllerTests.java
  src/test/java/com/yourney/controller/ItineraryControllerTests.java
  src/test/java/com/yourney/controller/LandmarkControllerTests.java
Labels: test

#56 Implementado plan de subscripción
  src/main/java/com/yourney/security/controller/AuthController.java
  src/main/java/com/yourney/security/service/UserService.java
Labels: enhancement

#58 Validación de registro e inicio de sesión
  src/main/java/com/yourney/security/controller/AuthController.java
  src/main/java/com/yourney/security/model/dto/LoginUser.java
  src/main/java/com/yourney/security/model/dto/NewUser.java
Labels: enhancement, invalid

#59 Corrección de configuración de SonarCloud para análisis de cobertura de código
  .travis.yml
  pom.xml
Labels: bug, configuration, invalid, test

#61 Añadido estado de itinerario a DTO y eliminada condición innecesaria
  src/main/java/com/yourney/controller/ActivityController.java
  src/main/java/com/yourney/model/dto/ItineraryDto.java
  src/main/java/com/yourney/model/projection/ItineraryProjection.java
Labels: bug

#62 Eliminada restricción innecesaria para actualizar una actividad
  src/main/java/com/yourney/controller/ActivityController.java
Labels: bug

#64 Añadido nuevo parámetro de búsqueda de itinerario
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/repository/ItineraryRepository.java
  src/main/java/com/yourney/service/ItineraryService.java
  src/test/java/com/yourney/controller/ActivityControllerTests.java
  src/test/java/com/yourney/controller/ItineraryControllerTests.java
  src/test/java/com/yourney/controller/LandmarkControllerTests.java
Labels: bug

#66 Actualización de listar mis itinerarios y correcciones de deficiencias en el código por SonarCloud
  pom.xml
  src/main/java/com/yourney/config/SecurityConfig.java
  src/main/java/com/yourney/controller/ActivityController.java
  src/main/java/com/yourney/controller/ImageController.java
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/model/dto/LandmarkDto.java
  src/main/java/com/yourney/model/projection/LandmarkProjection.java
  src/main/java/com/yourney/repository/ItineraryRepository.java
  src/main/java/com/yourney/security/controller/AuthController.java
  src/main/java/com/yourney/security/service/UserService.java
  src/main/java/com/yourney/service/CloudinaryService.java
  src/main/java/com/yourney/service/ItineraryService.java
  src/test/java/com/yourney/controller/ActivityControllerTests.java
  src/test/java/com/yourney/controller/ItineraryControllerTests.java
  src/test/java/com/yourney/controller/LandmarkControllerTests.java
Labels: bug, configuration

#77 Creación y eliminación de comentarios
  src/main/java/com/yourney/controller/ActivityController.java
  src/main/java/com/yourney/controller/CommentController.java
  src/main/java/com/yourney/model/Comment.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/dto/CommentDto.java
  src/main/java/com/yourney/model/dto/LandmarkDto.java
  src/main/java/com/yourney/repository/CommentRepository.java
  src/main/java/com/yourney/security/controller/AuthController.java
  src/main/java/com/yourney/service/CommentService.java
  src/main/resources/db/data.sql
Labels: enhancement

#78 Añadidos datos iniciales a BBDD
  src/main/resources/db/data.sql
  src/main/resources/db/data2.sql
Labels: enhancement

#79 Búsqueda de POI y gestión de imágenes para Landmark, Itinerario y Usuario
  src/main/java/com/yourney/controller/CommentController.java
  src/main/java/com/yourney/controller/ImageController.java
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/model/Comment.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/Landmark.java
  src/main/java/com/yourney/model/projection/AuthorProjection.java
  src/main/java/com/yourney/model/projection/LandmarkProjection.java
  src/main/java/com/yourney/repository/CommentRepository.java
  src/main/java/com/yourney/repository/ItineraryRepository.java
  src/main/java/com/yourney/repository/LandmarkRepository.java
  src/main/java/com/yourney/security/controller/AuthController.java
  src/main/java/com/yourney/security/model/User.java
  src/main/java/com/yourney/service/LandmarkService.java
  src/main/resources/db/data.sql
Labels: bug, enhancement

#85 Implementación para búsqueda priorizada de POI
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/Landmark.java
  src/main/java/com/yourney/model/projection/ItineraryProjection.java
  src/main/java/com/yourney/model/projection/LandmarkProjection.java
  src/main/java/com/yourney/repository/ItineraryRepository.java
  src/main/java/com/yourney/repository/LandmarkRepository.java
  src/main/java/com/yourney/service/LandmarkService.java
  src/main/resources/db/data.sql
  src/test/java/com/yourney/controller/ItineraryControllerTests.java
  src/test/java/com/yourney/controller/LandmarkControllerTests.java
Labels: bug, enhancement

#89 Pago de suscripciones a través de PayPal
  pom.xml
  src/main/java/com/yourney/paypal/config/PayPalConfiguration.java
  src/main/java/com/yourney/paypal/controller/PayPalController.java
  src/main/java/com/yourney/paypal/exception/CheckoutException.java
  src/main/java/com/yourney/paypal/service/CaptureOrderService.java
  src/main/java/com/yourney/paypal/service/CreateOrderService.java
  src/main/java/com/yourney/security/service/UserService.java
  src/main/resources/application.properties
Labels: enhancement

#91 Corrección de la solicitud de pago
  src/main/java/com/yourney/paypal/controller/PayPalController.java
Labels: bug

#92 Crear actividad mediante el identificador de un punto de interés
  src/main/java/com/yourney/controller/ActivityController.java
  src/test/java/com/yourney/controller/ActivityControllerTests.java
Labels: enhancement

#94 Corrección de error detectado en la actualización de usuario
  src/main/java/com/yourney/security/controller/AuthController.java
Labels: bug

#95 Feature issue#87
  src/main/java/com/yourney/repository/ItineraryRepository.java
Labels: bug

#97 Formato de los teléfonos actualizado
  src/main/java/com/yourney/paypal/service/CaptureOrderService.java
  src/main/java/com/yourney/security/model/dto/UpdateUser.java
  src/main/resources/db/data.sql
Labels: bug

#98 Patrocinio de puntos de interés
  src/main/java/com/yourney/paypal/controller/PayPalController.java
  src/main/java/com/yourney/paypal/service/CaptureOrderService.java
  src/main/java/com/yourney/paypal/service/CreateOrderService.java
Labels: enhancement

#99 Integración con Governify
  info.yml
Labels: configuration

#101 Correccion de errores de Governify
  info.yml
Labels: bug

#103 Creado fichero de configuración para Governify
  info.yml
Labels: configuration

#105 Restricciones de Landmark
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/model/Landmark.java
  src/main/java/com/yourney/model/SeasonType.java
  src/main/java/com/yourney/model/dto/LandmarkDto.java
Labels: bug, enhancement

#107 Aumento de límite de capacidad de persistencia para parámetros específicos
  src/main/java/com/yourney/model/Landmark.java
  src/main/java/com/yourney/model/dto/ActivityDto.java
  src/main/java/com/yourney/model/dto/CommentDto.java
  src/main/java/com/yourney/model/dto/ItineraryDto.java
  src/main/java/com/yourney/model/dto/LandmarkDto.java
Labels: bug

#108 Elaboración de pruebas para todas las funcionalidades de la aplicación
  pom.xml
  src/main/java/com/yourney/controller/CommentController.java
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/dto/ActivityDto.java
  src/main/java/com/yourney/model/dto/AuthorDto.java
  src/main/java/com/yourney/model/dto/CommentDto.java
  src/main/java/com/yourney/model/dto/ImageDto.java
  src/main/java/com/yourney/model/dto/ItineraryDto.java
  src/main/java/com/yourney/model/dto/LandmarkDto.java
  src/main/java/com/yourney/security/controller/AuthController.java
  src/main/java/com/yourney/security/model/dto/JwtDto.java
  src/test/java/com/yourney/controller/ActivityControllerTests.java
  src/test/java/com/yourney/controller/AuthControllerTests.java
  src/test/java/com/yourney/controller/CommentControllerTests.java
  src/test/java/com/yourney/controller/ImageControllerTests.java
  src/test/java/com/yourney/controller/ItineraryControllerTests.java
  src/test/java/com/yourney/controller/LandmarkControllerTests.java
  src/test/java/com/yourney/model/ActivityDtoModelTests.java
  src/test/java/com/yourney/model/AuthorDtoModelTests.java
  src/test/java/com/yourney/model/CommentDtoModelTests.java
  src/test/java/com/yourney/model/ImageDtoModelTests.java
  src/test/java/com/yourney/model/ItineraryDtoModelTests.java
  src/test/java/com/yourney/model/LandmarkDtoModelTests.java
  src/test/java/com/yourney/model/MessageDtoModelTests.java
  src/test/java/com/yourney/model/SearchDtoModelTests.java
  src/test/java/com/yourney/model/SeasonDtoModelTests.java
  src/test/java/com/yourney/model/security/JwtDtoModelTests.java
  src/test/java/com/yourney/model/security/LoginUserDtoModelTests.java
  src/test/java/com/yourney/model/security/NewUserDtoModelTests.java
  src/test/java/com/yourney/model/security/UpdateUserDtoModelTests.java
  src/test/java/com/yourney/service/ActivityServiceTests.java
  src/test/java/com/yourney/service/CommentServiceTests.java
  src/test/java/com/yourney/service/ImageServiceTests.java
  src/test/java/com/yourney/service/ItineraryServiceTests.java
  src/test/java/com/yourney/service/LandmarkServiceTests.java
  src/test/java/com/yourney/service/UserServiceTests.java
Labels: test

#110 Corrección de malos olores en las pruebas y añadido soporte para búsquedas en minúscula
  src/main/java/com/yourney/repository/LandmarkRepository.java
  src/test/java/com/yourney/model/ActivityDtoModelTests.java
  src/test/java/com/yourney/model/AuthorDtoModelTests.java
  src/test/java/com/yourney/model/CommentDtoModelTests.java
  src/test/java/com/yourney/model/ImageDtoModelTests.java
  src/test/java/com/yourney/model/ItineraryDtoModelTests.java
  src/test/java/com/yourney/model/LandmarkDtoModelTests.java
  src/test/java/com/yourney/model/MessageDtoModelTests.java
  src/test/java/com/yourney/model/SearchDtoModelTests.java
  src/test/java/com/yourney/model/SeasonDtoModelTests.java
  src/test/java/com/yourney/model/security/JwtDtoModelTests.java
  src/test/java/com/yourney/model/security/LoginUserDtoModelTests.java
  src/test/java/com/yourney/model/security/NewUserDtoModelTests.java
  src/test/java/com/yourney/model/security/UpdateUserDtoModelTests.java
  src/test/java/com/yourney/service/ActivityServiceTests.java
  src/test/java/com/yourney/service/ItineraryServiceTests.java
  src/test/java/com/yourney/service/LandmarkServiceTests.java
Labels: bug, configuration, test

#112 Orden de muestra de actividades
  src/main/java/com/yourney/controller/ActivityController.java
  src/main/java/com/yourney/controller/CommentController.java
  src/main/java/com/yourney/controller/ImageController.java
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/model/Activity.java
  src/main/java/com/yourney/model/Itinerary.java
  src/test/java/com/yourney/controller/ActivityControllerTests.java
  src/test/java/com/yourney/controller/CommentControllerTests.java
  src/test/java/com/yourney/controller/ImageControllerTests.java
  src/test/java/com/yourney/controller/ItineraryControllerTests.java
  src/test/java/com/yourney/controller/LandmarkControllerTests.java
Labels: bug

#115 Feature issue#114
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/repository/LandmarkRepository.java
  src/main/java/com/yourney/service/LandmarkService.java
  src/main/resources/db/data.sql
  src/test/java/com/yourney/controller/LandmarkControllerTests.java
  src/test/java/com/yourney/service/LandmarkServiceTests.java
Labels: enhancement

#116 Corrección de errores en las validaciones
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/Landmark.java
  src/main/java/com/yourney/model/dto/ActivityDto.java
  src/main/java/com/yourney/model/dto/CommentDto.java
  src/main/java/com/yourney/model/dto/ItineraryDto.java
  src/main/java/com/yourney/model/dto/LandmarkDto.java
  src/test/java/com/yourney/controller/LandmarkControllerTests.java
Labels: bug

#118 Feature 117
  pom.xml
  src/main/java/com/yourney/YourneyBackendApplication.java
  src/main/java/com/yourney/config/FileUploadExceptionAdvice.java
  src/main/java/com/yourney/config/MultipartConfig.java
  src/main/java/com/yourney/security/model/User.java
  src/main/java/com/yourney/security/model/dto/LoginUser.java
  src/main/java/com/yourney/security/model/dto/NewUser.java
  src/main/resources/db/data.sql
Labels: enhancement

#120 Corregidos datos de prueba
  src/main/resources/db/data.sql
Labels: bug

#122 Feature 121
  src/main/resources/db/data.sql
  src/test/java/com/yourney/controller/AuthControllerTests.java
Labels: enhancement

#126 Dashboard administrador
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/repository/ActivityRepository.java
  src/main/java/com/yourney/repository/ItineraryRepository.java
  src/main/java/com/yourney/repository/LandmarkRepository.java
  src/main/java/com/yourney/service/ItineraryService.java
  src/main/java/com/yourney/service/LandmarkService.java
  src/main/resources/db/data.sql
Labels: enhancement

#131 Mostrar número de comentarios
  src/main/java/com/yourney/model/projection/ItineraryProjection.java
Labels: enhancement

#132 Verificación de usuario por correo electrónico
  pom.xml
  src/main/java/com/yourney/YourneyBackendApplication.java
  src/main/java/com/yourney/security/controller/AuthController.java
  src/main/java/com/yourney/security/exception/UnverifiedUserException.java
  src/main/java/com/yourney/security/model/SecureToken.java
  src/main/java/com/yourney/security/model/User.java
  src/main/java/com/yourney/security/repository/SecureTokenRepository.java
  src/main/java/com/yourney/security/service/SecureTokenService.java
  src/main/java/com/yourney/security/service/UserDetailsServiceImpl.java
  src/main/java/com/yourney/security/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/db/data.sql
  src/main/resources/mail/index.html
  src/test/java/com/yourney/controller/AuthControllerTests.java
Labels: enhancement

#133 Feature issue#127
  src/main/java/com/yourney/controller/ActivityController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/service/LandmarkService.java
  src/test/java/com/yourney/controller/ActivityControllerTests.java
  src/test/java/com/yourney/controller/ItineraryControllerTests.java
  src/test/java/com/yourney/controller/LandmarkControllerTests.java
  src/test/java/com/yourney/service/ItineraryServiceTests.java
  src/test/java/com/yourney/service/LandmarkServiceTests.java
Labels: test

#135 Configuración de despliegue para el email
  src/main/resources/application.properties
Labels: bug

#137 Pruebas sobre AuthController
  src/main/java/com/yourney/security/controller/AuthController.java
  src/test/java/com/yourney/controller/AuthControllerTests.java
Labels: test

#139 Cambio de categorías de puntos de interés
  src/main/resources/db/data.sql
Labels: enhancement

#140 Configuración para la persistencia en la base de datos
  pom.xml
  src/main/resources/application-dev.properties
  src/main/resources/application-gen.properties
  src/main/resources/application-prod.properties
  src/main/resources/application-production.properties
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__create.sql
  src/main/resources/db/migration/V2__data.sql
Labels: enhancement

#142 Cambiado itinerary proyection
  src/main/java/com/yourney/model/projection/ItineraryProjection.java
Labels: enhancement

#148 Corrección de la plantilla de email
  src/main/resources/mail/index.html
Labels: bug

#146 Restricción en la publicación de comentarios
  src/main/java/com/yourney/controller/CommentController.java
  src/test/java/com/yourney/controller/CommentControllerTests.java
Labels: bug

#149 Verificación de visualizaciones de itinerario y punto de interés
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/ItineraryVisit.java
  src/main/java/com/yourney/model/Landmark.java
  src/main/java/com/yourney/model/LandmarkVisit.java
  src/main/java/com/yourney/repository/ItineraryVisitRepository.java
  src/main/java/com/yourney/repository/LandmarkVisitRepository.java
  src/main/java/com/yourney/service/ItineraryVisitService.java
  src/main/java/com/yourney/service/LandmarkVisitService.java
  src/main/resources/application.properties
  src/main/resources/db/data.sql
  src/main/resources/templates/banner.txt
  src/test/java/com/yourney/controller/ItineraryControllerTests.java
  src/test/java/com/yourney/controller/LandmarkControllerTests.java
  src/test/java/com/yourney/model/ItineraryVisitModelTests.java
  src/test/java/com/yourney/model/LandmarkVisitModelTests.java
Labels: bug
