Repository ispp-yourney/yourney-backend, pull requests merged in 2021-03, with the labels that each got.

#21 Implementación de herramientas de integración continua
  .gitignore
  .travis.yml
  README.md
  pom.xml
Labels: configuration

#24 Implementación inicial del modelo de datos
  .gitignore
  src/main/java/com/yourney/controller/LoginRestController.java
  src/main/java/com/yourney/controller/UserRestController.java
  src/main/java/com/yourney/dto/Message.java
  src/main/java/com/yourney/model/activities/Activity.java
  src/main/java/com/yourney/model/activities/Category.java
  src/main/java/com/yourney/model/activities/Contact.java
  src/main/java/com/yourney/model/activities/Image.java
  src/main/java/com/yourney/model/activities/Landmark.java
  src/main/java/com/yourney/model/itineraries/Itinerary.java
  src/main/java/com/yourney/model/itineraries/Season.java
  src/main/java/com/yourney/model/itineraries/SeasonType.java
  src/main/java/com/yourney/model/itineraries/StatusType.java
  src/main/resources/application-production.properties
  src/main/resources/db/data.sql
Labels: enhancement

#25 Eliminada una de las dos ejecuciones de los test
  .travis.yml
Labels: configuration

#26 Autenticación con JWT
  pom.xml
  src/main/java/com/yourney/config/ApplicationSecurity.java
  src/main/java/com/yourney/controller/LoginRestController.java
  src/main/java/com/yourney/controller/UserRestController.java
  src/main/java/com/yourney/model/itineraries/Itinerary.java
  src/main/java/com/yourney/model/users/User.java
  src/main/java/com/yourney/repository/users/UserRepository.java
  src/main/java/com/yourney/security/MainSecurity.java
  src/main/java/com/yourney/security/controller/AuthController.java
  src/main/java/com/yourney/security/dto/JwtDto.java
  src/main/java/com/yourney/security/dto/LoginUser.java
  src/main/java/com/yourney/security/dto/NewUser.java
  src/main/java/com/yourney/security/entity/PrincipalUser.java
  src/main/java/com/yourney/security/entity/Role.java
  src/main/java/com/yourney/security/entity/User.java
  src/main/java/com/yourney/security/enums/RoleType.java
  src/main/java/com/yourney/security/jwt/JwtEntryPoint.java
  src/main/java/com/yourney/security/jwt/JwtProvider.java
  src/main/java/com/yourney/security/jwt/JwtTokenFilter.java
  src/main/java/com/yourney/security/repository/RoleRepository.java
  src/main/java/com/yourney/security/repository/UserRepository.java
  src/main/java/com/yourney/security/service/RoleService.java
  src/main/java/com/yourney/security/service/UserDetailsServiceImpl.java
  src/main/java/com/yourney/security/service/UserService.java
  src/main/java/com/yourney/service/users/UserService.java
  src/main/resources/application.properties
  src/main/resources/db/data.sql
Labels: enhancement

#29 Integración de despliegue automatizado
  .travis.yml
  pom.xml
  system.properties
Labels: configuration

#31 Integración con Cloudinary
  pom.xml
  src/main/java/com/yourney/controller/ImageController.java
  src/main/java/com/yourney/model/Image.java
  src/main/java/com/yourney/model/dto/ImageDto.java
  src/main/java/com/yourney/model/projection/ImageProjection.java
  src/main/java/com/yourney/repository/ImageRepository.java
  src/main/java/com/yourney/service/CloudinaryService.java
  src/main/java/com/yourney/service/ImageService.java
  src/main/resources/application.properties
Labels: enhancement

#32 Implementación de consulta y eliminación de itinerarios
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/dto/AuthorDto.java
  src/main/java/com/yourney/model/dto/ItineraryDto.java
  src/main/java/com/yourney/model/projection/AuthorProjection.java
  src/main/java/com/yourney/model/projection/ItineraryProjection.java
  src/main/java/com/yourney/repository/ItineraryRepository.java
  src/main/java/com/yourney/service/ItineraryService.java
Labels: enhancement

#33 Feature 6
  src/main/java/com/yourney/config/SecurityConfig.java
  src/main/java/com/yourney/controller/ImageController.java
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/model/Activity.java
  src/main/java/com/yourney/model/Image.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/dto/ActivityDto.java
  src/main/java/com/yourney/model/dto/AuthorDto.java
  src/main/java/com/yourney/model/dto/ImageDto.java
  src/main/java/com/yourney/model/dto/ItineraryDto.java
  src/main/java/com/yourney/model/projection/AuthorProjection.java
  src/main/java/com/yourney/repository/ItineraryRepository.java
  src/main/java/com/yourney/repository/LandmarkRepository.java
  src/main/java/com/yourney/security/controller/AuthController.java
  src/main/java/com/yourney/security/model/User.java
  src/main/java/com/yourney/security/model/dto/LoginUser.java
  src/main/java/com/yourney/security/model/dto/NewUser.java
  src/main/java/com/yourney/service/CloudinaryService.java
  src/main/java/com/yourney/service/ItineraryService.java
  src/main/java/com/yourney/service/LandmarkService.java
Labels: enhancement

#34 Funcionalidad de actualizar y crear itinerarios
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/dto/ItineraryDto.java
  src/main/java/com/yourney/model/dto/SeasonDto.java
  src/main/java/com/yourney/model/projection/ItineraryProjection.java
  src/main/java/com/yourney/model/projection/SeasonProjection.java
  src/main/java/com/yourney/repository/ImageRepository.java
  src/main/java/com/yourney/repository/SeasonRepository.java
  src/main/java/com/yourney/security/model/User.java
  src/main/java/com/yourney/security/model/dto/NewUser.java
  src/main/java/com/yourney/service/ImageService.java
  src/main/java/com/yourney/service/ItineraryService.java
  src/main/java/com/yourney/service/SeasonService.java
Labels: enhancement

#36 Vista de detalles de Itinerario
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/model/projection/ActivityDetailsProjection.java
  src/main/java/com/yourney/model/projection/ItineraryDetailsProjection.java
  src/main/java/com/yourney/repository/ItineraryRepository.java
  src/main/java/com/yourney/security/model/User.java
  src/main/java/com/yourney/service/ItineraryService.java
  src/main/resources/db/data.sql
Labels: enhancement

#41 Creación de proyección de Itinerario
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/model/projection/ActivityDetailsProjection.java
  src/main/java/com/yourney/model/projection/ItineraryDetailsProjection.java
  src/main/java/com/yourney/repository/ItineraryRepository.java
  src/main/java/com/yourney/security/model/User.java
  src/main/java/com/yourney/service/ItineraryService.java
  src/main/resources/db/data.sql
Labels: enhancement, invalid

#46 Creación de priorización de itinerarios
  src/main/java/com/yourney/config/SecurityConfig.java
  src/main/java/com/yourney/controller/ActivityController.java
  src/main/java/com/yourney/controller/ImageController.java
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/Landmark.java
  src/main/java/com/yourney/model/projection/ActivityDetailsProjection.java
  src/main/java/com/yourney/model/projection/ItineraryProjection.java
  src/main/java/com/yourney/repository/ItineraryRepository.java
  src/main/java/com/yourney/repository/LandmarkRepository.java
  src/main/java/com/yourney/security/controller/AuthController.java
  src/main/java/com/yourney/security/model/User.java
  src/main/java/com/yourney/security/model/dto/JwtDto.java
  src/main/java/com/yourney/service/ItineraryService.java
  src/main/resources/db/data.sql
Labels: enhancement

#45 Operaciones CRUD para Landmark y Activity, y refactorización del código
  src/main/java/com/yourney/controller/ActivityController.java
  src/main/java/com/yourney/controller/ImageController.java
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/model/Activity.java
  src/main/java/com/yourney/model/BaseEntity.java
  src/main/java/com/yourney/model/Image.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/Landmark.java
  src/main/java/com/yourney/model/SeasonType.java
  src/main/java/com/yourney/model/StatusType.java
  src/main/java/com/yourney/model/dto/ActivityDto.java
  src/main/java/com/yourney/model/dto/ItineraryDto.java
  src/main/java/com/yourney/model/dto/LandmarkDto.java
  src/main/java/com/yourney/model/projection/ActivityDetailsProjection.java
  src/main/java/com/yourney/model/projection/ActivityProjection.java
  src/main/java/com/yourney/model/projection/AuthorProjection.java
  src/main/java/com/yourney/model/projection/ImageProjection.java
  src/main/java/com/yourney/model/projection/ItineraryDetailsProjection.java
  src/main/java/com/yourney/model/projection/ItineraryProjection.java
  src/main/java/com/yourney/model/projection/LandmarkProjection.java
  src/main/java/com/yourney/model/projection/SeasonProjection.java
  src/main/java/com/yourney/repository/ActivityRepository.java
  src/main/java/com/yourney/repository/ImageRepository.java
  src/main/java/com/yourney/repository/LandmarkRepository.java
  src/main/java/com/yourney/security/controller/AuthController.java
  src/main/java/com/yourney/security/jwt/JwtEntryPoint.java
  src/main/java/com/yourney/security/jwt/JwtProvider.java
  src/main/java/com/yourney/security/jwt/JwtTokenFilter.java
  src/main/java/com/yourney/security/model/PrincipalUser.java
  src/main/java/com/yourney/security/model/Role.java
  src/main/java/com/yourney/security/model/User.java
  src/main/java/com/yourney/security/model/dto/JwtDto.java
  src/main/java/com/yourney/security/model/dto/LoginUser.java
  src/main/java/com/yourney/security/model/dto/NewUser.java
  src/main/java/com/yourney/security/repository/RoleRepository.java
  src/main/java/com/yourney/security/repository/UserRepository.java
  src/main/java/com/yourney/security/service/RoleService.java
  src/main/java/com/yourney/security/service/UserDetailsServiceImpl.java
  src/main/java/com/yourney/security/service/UserService.java
  src/main/java/com/yourney/service/ActivityService.java
  src/main/java/com/yourney/service/CloudinaryService.java
  src/main/java/com/yourney/service/ImageService.java
  src/main/java/com/yourney/service/LandmarkService.java
  src/main/resources/db/data.sql
Labels: enhancement

#48 Refactorización del código
  src/main/java/com/yourney/controller/ActivityController.java
  src/main/java/com/yourney/controller/ImageController.java
  src/main/java/com/yourney/controller/ItineraryController.java
  src/main/java/com/yourney/controller/LandmarkController.java
  src/main/java/com/yourney/model/Activity.java
  src/main/java/com/yourney/model/BaseEntity.java
  src/main/java/com/yourney/model/Image.java
  src/main/java/com/yourney/model/Itinerary.java
  src/main/java/com/yourney/model/Landmark.java
  src/main/java/com/yourney/model/StatusType.java
  src/main/java/com/yourney/model/dto/ActivityDto.java
  src/main/java/com/yourney/model/dto/AuthorDto.java
  src/main/java/com/yourney/model/dto/ItineraryDto.java
  src/main/java/com/yourney/model/dto/LandmarkDto.java
  src/main/java/com/yourney/model/dto/Message.java
  src/main/java/com/yourney/model/dto/Search.java
  src/main/java/com/yourney/model/dto/SeasonDto.java
  src/main/java/com/yourney/model/projection/ActivityDetailsProjection.java
  src/main/java/com/yourney/model/projection/ActivityProjection.java
  src/main/java/com/yourney/model/projection/ItineraryDetailsProjection.java
  src/main/java/com/yourney/model/projection/ItineraryProjection.java
  src/main/java/com/yourney/model/projection/LandmarkProjection.java
  src/main/java/com/yourney/repository/ActivityRepository.java
  src/main/java/com/yourney/repository/ImageRepository.java
  src/main/java/com/yourney/repository/ItineraryRepository.java
  src/main/java/com/yourney/repository/LandmarkRepository.java
  src/main/java/com/yourney/security/model/User.java
  src/main/java/com/yourney/service/ActivityService.java
  src/main/java/com/yourney/service/ImageService.java
  src/main/java/com/yourney/service/ItineraryService.java
  src/main/java/com/yourney/service/LandmarkService.java
  src/main/java/com/yourney/utils/ValidationUtils.java
  src/main/resources/db/data.sql
Labels: bug, enhancement

#51 Vista de información de usuario
  src/main/java/com/yourney/config/SwaggerConfig.java
  src/main/java/com/yourney/security/controller/AuthController.java
Labels: enhancement
